### ISSUE TITLE
Bug with text formatted with tspans

### ISSUE THREAD

**Issue by ninique** [dowjones/svg-text#4]
When you have more than one `<tspan>` in your text, all the lines that are between the one with the first <tspan> and the next one end up having the same style as the first <tspan>. 

Here is a JSfiddle showing the issue:
https://jsfiddle.net/8w1mt7py/

The words "adipisci velit" are supposed to be bold and "modi" is supposed to be red, but everything from the next line after "adipsci velit" until the one with "modi" in it is also bold.

**Comment by adrianlafond** [comment]
Thanks for catching that. I'll have a look and try to fix.
